name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'  # Adjust based on your Next.js version
          cache: 'npm'

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Build Next.js app
      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      # Only proceed with deployment if build succeeds
      - name: Deploy to Production Server
        if: success()  # This ensures deployment only runs if previous steps succeed
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p /var/www/panel.dbcvision.uz
            echo "Deployment directory prepared"

      # Copy files only if build succeeds
      - name: Copy Files to Server
        if: success()
        run: |
          scp -r ./.next/* ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/var/www/panel.dbcvision.uz/
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
