name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'  # Adjust based on your Next.js version
          cache: 'npm'

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Build Next.js app
      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      # Deploy to Production Server (create directory and copy files)
      - name: Deploy to Production Server
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p /var/www/panel.dbcvision.uz
            echo "Deployment directory prepared"
      # Copy files using scp within the ssh-action
      - name: Copy Files to Server
        if: success()
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "./.next/*"
          target: "/var/www/panel.dbcvision.uz/"
          strip_components: 1  # Ensures files are copied directly into the target directory