name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'  # Adjust based on your Next.js version
          cache: 'npm'

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Build Next.js app
      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      # Set up SSH key for deployment
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      # Deploy to Production Server (create directory)
      - name: Deploy to Production Server
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p /var/www/panel.dbcvision.uz
            echo "Deployment directory prepared"

      # Copy files to server
      - name: Copy Files to Server
        if: success()
        run: |
          scp -r -o StrictHostKeyChecking=no ./.next/* ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/var/www/panel.dbcvision.uz/
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock